version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: pfe_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5433:5432"
    volumes:
      - ./config/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./config/database/init-log-directory.sh:/docker-entrypoint-initdb.d/init-log-directory.sh
      # - ./config/database/postgres.conf:/etc/postgresql/postgresql.conf
      # - ./logs/:/var/log/postgresql/
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: docker/api.dockerfile
    environment:
      PG_USER: admin_user
      PG_PASSWORD: admin_password
      PG_HOST: postgres
      PG_DATABASE: postgres
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
    restart: on-failure

  front:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    container_name: front
    networks:
      - frontend
    ports:
      - "3000:3000"
        

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

# volumes:
#   postgres_data:
