CREATE ROLE minimal_user WITH LOGIN PASSWORD 'my_password';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO minimal_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO my_user;

CREATE TABLE IF NOT EXISTS MyUser (
    auth_id UUID PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);
