apiVersion: v1
data:
  PG_DATABASE: cGZlX2RhdGFiYXNlCg==
  PG_PASSWORD: cG9zdGdyZXMK
  PG_USER: YWRtaW5fdXNlcgo=
  PG_HOST: cG9zdGdyZXMK
  DATABASE: cGZlX2RhdGFiYXNlCg==
  USER: bXlfdXNlcgo=
  PASSWORD: bXlfcGFzc3dvcmQK
  HOST: cG9zdGdyZXMK
  PORT: NTQzMgo=
  AUTH_DATABASE: cGZlX2RhdGFiYXNlX2F1dGgK
  AUTH_USER: bXlfdXNlcgo=
  AUTH_PASSWORD: bXlfcGFzc3dvcmQK
  AUTH_HOST: YXV0aF9kYgo=
  AUTH_PORT: NTQzMgo=
kind: Secret
metadata:
  creationTimestamp: null
  name: messecure-secrets2
  namespace: messecure-ns
